package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.example.jdbcdemo.domain.Car;

public class CarManager {
	private Connection connection;
	private Statement statement;
	
	public String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createCarTable ="create table Car(id bigint GENERATED BY DEFAULT AS IDENTITY, model varchar(20), yop integer)";

	public CarManager() {
		
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Car".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			
			if (!tableExists)
				statement.executeUpdate(createCarTable);
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	

	public Connection getConnection() {
		return connection;
	}



	public void setConnection(Connection connection) {
		this.connection = connection;
	}



	public void addCar(Car car){
		try {
			statement.executeUpdate("insert into Car values( " + car.getModel() + "," + car.getYop() +" )");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
